# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         VSAP-Server-Modules-vsap-config
version:      1.06
version_from: lib/VSAP/Server/Modules/vsap/config.pm
installdirs:  vendor
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
